export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  PHARMACIST: "PHARMACIST",
  LABORATORY: "LABORATORY",
  RECEPTIONIST: "RECEPTIONIST",
  BILLING: "BILLING",
  PATIENT: "PATIENT",
} as const;